package com.bob.flyboymvp.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bob.flyboymvp.model.PerAddrInfo;
import com.bob.flyboymvp.model.PerSocialInfor;
import com.bob.flyboymvp.model.UserInfo;

import com.bob.flyboymvp.dao.PerAddrInfoDao;
import com.bob.flyboymvp.dao.PerSocialInforDao;
import com.bob.flyboymvp.dao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig perAddrInfoDaoConfig;
    private final DaoConfig perSocialInforDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final PerAddrInfoDao perAddrInfoDao;
    private final PerSocialInforDao perSocialInforDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        perAddrInfoDaoConfig = daoConfigMap.get(PerAddrInfoDao.class).clone();
        perAddrInfoDaoConfig.initIdentityScope(type);

        perSocialInforDaoConfig = daoConfigMap.get(PerSocialInforDao.class).clone();
        perSocialInforDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        perAddrInfoDao = new PerAddrInfoDao(perAddrInfoDaoConfig, this);
        perSocialInforDao = new PerSocialInforDao(perSocialInforDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(PerAddrInfo.class, perAddrInfoDao);
        registerDao(PerSocialInfor.class, perSocialInforDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        perAddrInfoDaoConfig.clearIdentityScope();
        perSocialInforDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public PerAddrInfoDao getPerAddrInfoDao() {
        return perAddrInfoDao;
    }

    public PerSocialInforDao getPerSocialInforDao() {
        return perSocialInforDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
